sap.ui.define([
    "demo/model/BaseObject"
  ], function (BaseObject) {
    "use strict";
    return BaseObject.extend("demo.model.Data", {
      constructor: function () {
        BaseObject.call(this);
        this.returnData = returnData;
      }
    });
    function returnData(val1,val2,val3,val4,val5,val6) {
        const data = {
            "Shipments": [
              {
                "Hall" : "1C",
                "ShipperName" : "Duvenbeck",
                "Tknum" : "123454115",
                "Kunwe" : "200730",
                "Tdlnr" : "100578",
                "Asn" : false,
                "Signi" : "3P7 1918",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis1",
                "Dptbg" : "\/Date(1679821440000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT12H00M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "62",
                "TotalHu" : "64",
                "Meins" : "PC",
                "CustomerName" : "Dr. Ing. h.c. F. Porsche AG",
                "Werks" : "",
                "Lgnum" : "220",
                "Vstel" : "2200",
                "Ablad" : "CZ22B"
              },
              {
                "Hall" : "7B",
                "ShipperName" : "Duvenbeck",
                "Tknum" : "6758125559",
                "Kunwe" : "2220",
                "Tdlnr" : "199574",
                "Asn" : false,
                "Signi" : "7A1 1993",
                "Exti1" : "Ano",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis8",
                "Dptbg" : "\/Date(1679907840000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT18H30M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : '130',
                "TotalHu" : "200",
                "Meins" : "PC",
                "CustomerName" : "Volkswagen AG",
                "Werks" : "",
                "Lgnum" : "220",
                "Vstel" : "2200",
                "Ablad" : "CZ11B"
              },
              {
                "Hall" : "1AA",
                "ShipperName" : "DHL",
                "Tknum" : "645485789",
                "Kunwe" : "22420",
                "Tdlnr" : "100574",
                "Asn" : false,
                "Signi" : "1AF 7842",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis1",
                "Dptbg" : "\/Date(1678356240000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT10H00M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "23",
                "TotalHu" : "100",
                "Meins" : "PC",
                "CustomerName" : "Aston Martin",
                "Werks" : "",
                "Lgnum" : "220",
                "Vstel" : "1346",
                "Ablad" : "CZ11C"
              },
              {
                "Hall" : "1C",
                "ShipperName" : "Duvenbeck",
                "Tknum" : "652245489",
                "Kunwe" : "220720",
                "Tdlnr" : "109572",
                "Asn" : true,
                "Signi" : "8C7 1989",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis4",
                "Dptbg" : "\/Date(1678874640000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT12H00M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "0",
                "TotalHu" : "90",
                "Meins" : "PC",
                "CustomerName" : "Volkswagen AG",
                "Werks" : "",
                "Lgnum" : "220",
                "Vstel" : "2200",
                "Ablad" : "CZ11B"
              },
              {
                "Hall" : "1B",
                "ShipperName" : "DHL",
                "Tknum" : "678022789",
                "Kunwe" : "220720",
                "Tdlnr" : "199574",
                "Asn" : true,
                "Signi" : "8AY 1620",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis2",
                "Dptbg" : "\/Date(1679479440000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT08H30M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "20",
                "TotalHu" : "180",
                "Meins" : "PC",
                "CustomerName" : "Volkswagen AG",
                "Werks" : "",
                "Lgnum" : "220",
                "Vstel" : "1945",
                "Ablad" : "CZ11B"
              },
              {
                "Hall" : "1F",
                "ShipperName" : "DHL",
                "Tknum" : "601511700",
                "Kunwe" : "220720",
                "Tdlnr" : "199574",
                "Asn" : false,
                "Signi" : "6AY 1942",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis1",
                "Dptbg" : "\/Date(1674169200000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT17H20M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "10",
                "TotalHu" : "100",
                "Meins" : "PC",
                "CustomerName" : "Škoda Auto",
                "Werks" : "",
                "Lgnum" : "120",
                "Vstel" : "1111",
                "Ablad" : "CZ11C"
              },
              {
                "Hall" : "5F",
                "ShipperName" : "DHL",
                "Tknum" : "601001700",
                "Kunwe" : "227720",
                "Tdlnr" : "100574",
                "Asn" : false,
                "Signi" : "7AY 1102",
                "Exti1" : "není",
                "PackInfo" : "pouze boxy",
                "Disponent" : "Dis2",
                "Dptbg" : "\/Date(1674060020000)\/",
                "PackType" : "klasický vývoz",
                "Uptbg" : "PT17H10M00S",
                "Exti2" : "CZDRJA",
                "Tpbez" : "klasický vývoz",
                "ClosedHu" : "165",
                "TotalHu" : "170",
                "Meins" : "PC",
                "CustomerName" : "Škoda Auto",
                "Werks" : "",
                "Lgnum" : "110",
                "Vstel" : "1151",
                "Ablad" : "CZ00C"
              }
            ]
        }
        return data
    }
});
  